"""Write a Markdown report for each completed month: reports/YYYY-MM.md.

A month is reported once its last day is in aqi_daily.csv and at least
MIN_DAYS of it have data. Reports are immutable records, like the CSVs:
an existing file is never rewritten.
"""

from __future__ import annotations

import calendar
import sys
from collections import Counter
from datetime import date
from pathlib import Path

from common import (
    CITIES,
    DAILY_CSV_PATH,
    GASES_CSV_PATH,
    NAQI_CATEGORIES,
    NAQI_SEVERE,
    ROOT,
    aqi_category,
    naqi,
    read_rows,
)

REPORTS_DIR = ROOT / "reports"
MIN_DAYS = 20  # a month with fewer days of data isn't worth summarising
INDEX_NAME = "README.md"  # GitHub shows it when browsing reports/


def complete_months(daily_rows: list[dict[str, str]]) -> list[str]:
    """'YYYY-MM' for each month whose last day is present and has >= MIN_DAYS days."""
    days = {r["date"] for r in daily_rows}
    months = sorted({d[:7] for d in days})
    result = []
    for month in months:
        year, mon = map(int, month.split("-"))
        last = date(year, mon, calendar.monthrange(year, mon)[1]).isoformat()
        if last in days and sum(d.startswith(month) for d in days) >= MIN_DAYS:
            result.append(month)
    return result


def _india(row: dict[str, str], gas: dict[str, str]):
    # Same rule as the README: no O₃ (CAMS surface ozone is biased high over India).
    return naqi(row.get("pm2_5_mean"), row.get("pm10_mean"), gas.get("no2_mean"))


def render_month(
    month: str, daily_rows: list[dict[str, str]], gas_rows: list[dict[str, str]]
) -> str:
    year, mon = map(int, month.split("-"))
    title = f"{calendar.month_name[mon]} {year}"
    rows = [r for r in daily_rows if r["date"].startswith(month) and r["us_aqi_mean"]]
    gases = {(g["date"], g["city"]): g for g in gas_rows}
    n_days = len({r["date"] for r in rows})
    categories = [label for _, label in NAQI_CATEGORIES] + [NAQI_SEVERE]

    summary = []
    for city, _, _ in CITIES:
        city_rows = sorted((r for r in rows if r["city"] == city), key=lambda r: r["date"])
        if not city_rows:
            continue
        us = [float(r["us_aqi_mean"]) for r in city_rows]
        india = [_india(r, gases.get((r["date"], city), {})) for r in city_rows]
        india = [x for x in india if x.category != "N/A"]
        worst = max(city_rows, key=lambda r: (float(r["us_aqi_mean"]), r["date"]))
        summary.append({
            "city": city,
            "days": len(city_rows),
            "us_mean": sum(us) / len(us),
            "cats": Counter(x.category for x in india),
            "prominent": Counter(x.prominent for x in india),
            "bad_days": sum(x.category in categories[3:] for x in india),  # Poor or worse
            "worst": worst,
        })

    lines = [
        f"# Air quality report: {title}",
        "",
        f"Full-day means for {n_days} days of {title}, from the CAMS model via Open-Meteo "
        "(CC BY 4.0). India AQI uses CPCB's scale with PM2.5, PM10 and NO₂; see the "
        "[README caveats](../README.md#caveats) for what these model values can and "
        "can't tell you.",
        "",
        "## Ranking (cleanest first, by mean US AQI)",
        "",
        "| # | City | Mean US AQI | Category | Days Poor or worse (India) | Worst day |",
        "|--:|---|--:|---|--:|---|",
    ]
    for i, s in enumerate(sorted(summary, key=lambda s: (s["us_mean"], s["city"])), start=1):
        worst = s["worst"]
        lines.append(
            f"| {i} | {s['city']} | {s['us_mean']:.0f} | {aqi_category(s['us_mean'])} | "
            f"{s['bad_days']} | {float(worst['us_aqi_mean']):.0f} on {worst['date']} |"
        )

    lines += [
        "",
        "## Days in each India AQI category",
        "",
        f"| City | {' | '.join(categories)} | Main pollutants |",
        "|---|" + "--:|" * len(categories) + "---|",
    ]
    for s in summary:
        cells = " | ".join(str(s["cats"][c]) if s["cats"][c] else "·" for c in categories)
        main = " · ".join(
            f"{name} {n}" for name, n in sorted(s["prominent"].items(), key=lambda kv: (-kv[1], kv[0]))
        )
        partial = f" ({s['days']} days)" if s["days"] < n_days else ""
        lines.append(f"| {s['city']}{partial} | {cells} | {main} |")

    lines += [
        "",
        "<sub>Generated by `report.py` from `data/aqi_daily.csv` and "
        "`data/aqi_daily_gases.csv`. Written once when the month completes; not updated "
        "afterwards.</sub>",
        "",
    ]
    return "\n".join(lines)


def write_reports(
    daily_rows: list[dict[str, str]],
    gas_rows: list[dict[str, str]],
    reports_dir: Path = REPORTS_DIR,
) -> list[Path]:
    """Write reports for completed months that don't have one yet."""
    written = []
    for month in complete_months(daily_rows):
        path = reports_dir / f"{month}.md"
        if path.exists():
            continue  # immutable once written
        reports_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(render_month(month, daily_rows, gas_rows), encoding="utf-8")
        written.append(path)
    return written


def report_months(reports_dir: Path = REPORTS_DIR) -> list[str]:
    """'YYYY-MM' of the reports on disk, oldest first."""
    return sorted(p.stem for p in reports_dir.glob("????-??.md"))


def render_index(months: list[str]) -> str:
    """reports/README.md: one row per year (newest first), one column per month."""
    by_year: dict[str, dict[int, str]] = {}
    for m in months:
        by_year.setdefault(m[:4], {})[int(m[5:])] = m
    abbr = [calendar.month_abbr[i] for i in range(1, 13)]
    lines = [
        "# Monthly air quality reports",
        "",
        f"{len(months)} report{'s' if len(months) != 1 else ''}, one per completed month, "
        "each written once and never updated. Compare cities within a month, not the same "
        "month across years: the CAMS model changed over this period (see the "
        "[README caveats](../README.md#caveats)).",
        "",
        f"| Year | {' | '.join(abbr)} |",
        "|---|" + ":-:|" * 12,
    ]
    for year in sorted(by_year, reverse=True):
        cells = [
            f"[{abbr[i - 1]}]({by_year[year][i]}.md)" if i in by_year[year] else "·"
            for i in range(1, 13)
        ]
        lines.append(f"| {year} | {' | '.join(cells)} |")
    lines += ["", "<sub>Generated by `report.py`; rewritten on every run.</sub>", ""]
    return "\n".join(lines)


def write_index(reports_dir: Path = REPORTS_DIR) -> Path | None:
    """Regenerate the index (it's a view of the reports, not a record); None if no reports."""
    months = report_months(reports_dir)
    if not months:
        return None
    path = reports_dir / INDEX_NAME
    path.write_text(render_index(months), encoding="utf-8")
    return path


def main(
    daily_csv_path: Path = DAILY_CSV_PATH,
    gases_csv_path: Path = GASES_CSV_PATH,
    reports_dir: Path = REPORTS_DIR,
) -> int:
    written = write_reports(read_rows(daily_csv_path), read_rows(gases_csv_path), reports_dir)
    for path in written:
        print(f"Wrote {path}")
    if not written:
        print("No new monthly reports.")
    if write_index(reports_dir):
        print(f"Updated {reports_dir / INDEX_NAME}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
